name: Nightly Unstable Build and Package

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test-unstable:
    uses: redis/docker-library-redis/.github/workflows/pre-merge.yml@unstable

