name: Nightly Unstable Build and Package

on:
  schedule:
    - cron: '0 1 * * *'  # Run every day at 1:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test-unstable:
    uses: ./.github/workflows/pre-merge.yml@unstable
    with:
      ref: 'unstable'
