name: Build and Test Unstable
on:
  pull_request:
    branches:
      - unstable

jobs:
  build-and-test:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - debian
          - alpine
        platform:
          - linux/amd64
          - linux/i386
          - linux/arm/v5
          - linux/arm/v6
          - linux/arm/v7
          - linux/mips64le
          - linux/ppc64le
          - linux/s390x
#          - linux/arm64
          - linux/riscv64
        exclude:
        - distribution: alpine
          platform: linux/mips64le
        - distribution: alpine
          platform: linux/arm/v5
        - distribution: debian
          platform: linux/riscv64
        - distribution: debian
          platform: linux/arm/v6
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-tag-locally
        with:
          distribution: ${{ matrix.distribution }}
          platform: ${{ matrix.platform }}
          registry_username: ${{ vars.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          publish_image: ${{ vars.PUBLISH_IMAGE }}
          registry_repository: ${{ vars.REGISTRY_REPOSITORY }}
